MTRProject/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using MTRProject.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MTRProject.Repositories;
using Microsoft.EntityFrameworkCore;

namespace MTRProject.Controllers
{
    public class AdminController : Controller
    {
        private IApplicationUserRepository userRepo;
        private UserManager<ApplicationUser> userManager;
        private RoleManager<IdentityRole> roleManager;

        public AdminController(UserManager<ApplicationUser> um, RoleManager<IdentityRole> rm, IApplicationUserRepository repo)
        {
            userManager = um;
            roleManager = rm;
            userRepo = repo;
        }

        public IActionResult Index()
        {
            return View();
        }

        public ViewResult ShowAccounts()
        {
            return View(userManager.Users);
        }


        public ViewResult CreateAccount() => View();

        [HttpPost]
        public async Task<IActionResult> CreateAccount(AccountViewModel model)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser user = new ApplicationUser
                {
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    UserName = model.UserName,
                    Email = model.Email,
                    IsSalesRep = model.IsSalesRep
                };

                IdentityResult result
                    = await userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("ShowAccounts");
                }
                else
                {
                    foreach (IdentityError error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }
            }
            return View(model);
        }

        public IActionResult EditAccount(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = userRepo.GetUserByUserName(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditAccount(string id, [Bind("Id,FirstName,LastName,UserName,Email,Password,IsSalesRep")] ApplicationUser user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                userRepo.EditUser(user);
                return RedirectToAction(nameof(ShowAccounts));
            }

            
           
            return View(user);
        }

        //public IActionResult DeleteAccount(string id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var user = userRepo.GetUserByUserName(id);
        //    if (user == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(user);
        //}

        //// POST: Sales/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public IActionResult DeleteConfirmed(string id)
        //{
        //    var user = userRepo.DeleteUser(id);
        //    return RedirectToAction(nameof(Index));
        //}


        /* ******************* *
       * Role administration *
       * ******************* */

        public ViewResult ShowRoles() => View(roleManager.Roles);

        public IActionResult CreateRole() => View();

        [HttpPost]
        public async Task<IActionResult> CreateRole([Required]string name)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result
                    = await roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("ShowRoles");
                }
                else
                {
                    AddErrorsFromResult(result);
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteRole(string id)
        {
            IdentityRole role = await roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await roleManager.DeleteAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrorsFromResult(result);
                }
            }
            else
            {
                ModelState.AddModelError("", "No role found");
            }
            return View("Index", roleManager.Roles);
        }

        private void AddErrorsFromResult(IdentityResult result)
        {
            foreach (IdentityError error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
        }

        public async Task<IActionResult> EditRoles(string id)
        {
            IdentityRole role = await roleManager.FindByIdAsync(id);
            List<ApplicationUser> members = new List<ApplicationUser>();
            List<ApplicationUser> nonMembers = new List<ApplicationUser>();
            foreach (ApplicationUser user in userManager.Users)
            {
                var list = await userManager.IsInRoleAsync(user, role.Name)
                ? members : nonMembers;
                list.Add(user);
            }
            return View(new RoleEditModel
            {
                Role = role,
                Members = members,
                NonMembers = nonMembers
            });
        }

        [HttpPost]
        public async Task<IActionResult> EditRoles(RoleModificationModel model)
        {
            IdentityResult result;
            if (ModelState.IsValid)
            {
                foreach (string userId in model.IdsToAdd ?? new string[] { })
                {
                    ApplicationUser user = await userManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        result = await userManager.AddToRoleAsync(user,
                        model.RoleName);
                        if (!result.Succeeded)
                        {
                            AddErrorsFromResult(result);
                        }
                    }
                }

                foreach (string userId in model.IdsToDelete ?? new string[] { })
                {
                    ApplicationUser user = await userManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        result = await userManager.RemoveFromRoleAsync(user,
                        model.RoleName);
                        if (!result.Succeeded)
                        {
                            AddErrorsFromResult(result);
                        }
                    }
                }
            }

            if (ModelState.IsValid)
            {
                return RedirectToAction(nameof(ShowRoles));
            }
            else
            {
                return await EditRoles(model.RoleId);
            }
        }












    }
}

MTRProject/Controllers/SalesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MTRProject.Data;
using MTRProject.Models;
using MTRProject.Repositories;
using Microsoft.AspNetCore.Identity;


namespace MTRProject.Controllers
{
    public class SalesController : Controller
    {

        private ISaleRepository saleRepo;
        private IApplicationUserRepository userRepo;
        private readonly UserManager<ApplicationUser> _userManager;

        //I added the following 3 lines of code to see if we could use both variations of this code(above and below)
        public SalesController(ISaleRepository repo, UserManager<ApplicationUser> userManager, IApplicationUserRepository uRepo)
        {
            saleRepo = repo;
            _userManager = userManager;
            userRepo = uRepo;
        }

        public string GetCurrentUserId() => _userManager.GetUserAsync(HttpContext.User).Result.Id ?? 0.ToString();

        // GET: Sales

		public IActionResult Summary()
        {
            return View(saleRepo.GetSummary());
            //return View(repController.OrderRepsByLastMonthSales(DateTime.Today));
        }
        
        public IActionResult Index()
        {
            var id = GetCurrentUserId();
            ApplicationUser user = userRepo.GetUserByUserName(id);
            return View(saleRepo.GetSalesByRep(user));
        }

        // GET: Sales/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sale = saleRepo.GetSaleById(id.GetValueOrDefault());
            if (sale == null)
            {
                return NotFound();
            }

            return View(sale);
        }

        // GET: Sales/Create
        public IActionResult Create()
        {
            Sale sale = new Sale();
            sale.DateEntered = DateTime.Today;
            sale.SaleDate = DateTime.Today;
            return View(sale);
        }

        // POST: Sales/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("SaleID,SaleTotal,DateEntered,SaleDate")] Sale sale)
        {
            if (ModelState.IsValid)
            {
                var id = GetCurrentUserId();
                saleRepo.AddSale(sale, id);
                return RedirectToAction(nameof(Index));
            }
            return View(sale);
        }

        // GET: Sales/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sale = saleRepo.GetSaleById(id.GetValueOrDefault());
            if (sale == null)
            {
                return NotFound();
            }

            return View(sale);

        }

        // POST: Sales/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("SaleID,SaleTotal,DateEntered,SaleDate")] Sale sale)
        {
            if (id != sale.SaleID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    saleRepo.EditSale(sale);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SaleExists(sale.SaleID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(sale);
        }

        // GET: Sales/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sale = saleRepo.GetSaleById(id.GetValueOrDefault());
            if (sale == null)
            {
                return NotFound();
            }

            return View(sale);
        }

        // POST: Sales/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var sale = saleRepo.DeleteSale(id);
            return RedirectToAction(nameof(Index));
        }

        private bool SaleExists(int id)
        {
            Sale sale = saleRepo.GetSaleById(id);
            if (sale != null)
                return true;
            else
                return false;
        }


        /******* CALCULATIONS *******/

        // returns CURRENT weekly total (TESTED )
        public decimal WeeklyTotal()
        {
			// gets "today"
			DateTime day = DateTime.Today;

            // calculates "this week" total and returns it
			return GetAllRepsWeeklySales(day);             
        }

		//Returns CURRENT month total (TESTED)
		public decimal MonthlyTotal()
        {
            // gets "today"
            DateTime day = DateTime.Today;

			// calculates "this month" total and returns it
			return GetAllRepsMonthlySalesTotal(day);
        }

		// This method returns the total sales for a day (TESTED)
		public decimal GetAllRepsDailySales(DateTime day)
        {
            decimal totalSales = 0;
            
			List<Sale> allSales = saleRepo.GetAllSales();
            
			//iterate through list and total each sale
            foreach (Sale s in allSales)
            {
				if(s.SaleDate == day)
                    totalSales += s.SaleTotal;
            }
            //return total
            return totalSales;
        }

		//This method returns the SalesEntered total per week for all reps (TESTED)
        public decimal GetAllRepsWeeklySales(DateTime day)
        {
            decimal totalSales = 0;

			//Gets day of week represented as an integer
			int dayOfWeek = (int)day.DayOfWeek;

            //determines sunday for calculations for the week
			var sunday = day.AddDays(-(int)DateTime.Today.DayOfWeek);
            
			List<Sale> allSales = saleRepo.GetAllSales();
			//iterate through list and total each sale
            foreach (Sale s in allSales)
            {
				if (s.SaleDate >= sunday && s.SaleDate <= sunday.AddDays(6))
				{
					totalSales += s.SaleTotal;
				}
					  
            }
            
            //return total
            return totalSales;
        }

		// Takes in a day and gets total from first of month to that day (TESTED)
		public decimal GetAllRepsMonthlySalesTotal(DateTime day)
        {
            decimal totalSales = 0;

            //Gets day of week represented as an integer
            int dayOfWeek = (int)day.DayOfWeek;
                        
			//determines 1st of month for calculations
			var firstOfMonth = new DateTime(day.Year, day.Month, 1);

			//access list of sales and create list where date range is "this" month 
			List<Sale> MonthlySales = saleRepo.GetAllSales();

            //iterate through list and total each sale
            foreach (Sale s in MonthlySales)
            {
				if(s.SaleDate <= day && s.SaleDate >= firstOfMonth)
                    totalSales += s.SaleTotal;
            }
            
            return totalSales;
        }

		// gets current year to date total for all reps (TESTED) 
		// -- needs code for year Changed in method for testing purposes --
		public decimal GetAllRepsYearSalesToDate()
		{
			decimal totalSales = 0;
           
			//determines 1st of year
			DateTime nowDate = DateTime.Today;

            // Fake nowDate for testing. Using DateTime.Now got 
			//tricky because the seed data came into play. (Passed)
			//DateTime nowDate = new DateTime(2016, 06, 01);

			DateTime first = new DateTime(nowDate.Year, 1, 1);

			//access list of sales 
			var all = saleRepo.GetAllSales();

			var ytdSales = GetSalesByDateRange(first, nowDate) as List<Sale>;

			foreach (Sale l in ytdSales)
			{
				totalSales += l.SaleTotal;
			}

			return totalSales;
		}
        

		// Get Monthly sales by rep for previous year (TESTED)
        public decimal GetLastYearThisMonthSalesTotal(DateTime day)
        {
            decimal totalSales = 0;
          
            //Gets day of week represented as an integer
            int dayOfWeek = (int)day.DayOfWeek;

            //determines 1st of month for calculations
            var lastYearFirst = new DateTime(day.Year - 1, 01, 01);
            var lastYearDays = DateTime.DaysInMonth(day.Year - 1, day.Month);
            var lastYearLast = new DateTime(day.Year - 1 , day.Month, lastYearDays);
            
			var lastYearMonth = GetSalesByDateRange(lastYearFirst, lastYearLast) as List<Sale>;

			foreach(Sale l in lastYearMonth)
			{
				totalSales += l.SaleTotal;
			}

            return totalSales;
        }
        

		// Calculates total sales for a given date (TESTED)
		public List<Sale> GetSalesByDate(DateTime date)
        {
            List<Sale> list = saleRepo.GetAllSales();
            List<Sale> dateSales = new List<Sale>();


            foreach (Sale s in list)
            {

                if (s.SaleDate == date)
                    dateSales.Add(s);

            }

            return dateSales;

        }

		// Calculates total sales for a given date range (TESTED)
        public List<Sale> GetSalesByDateRange(DateTime date1, DateTime date2)
        {
			List<Sale> list = saleRepo.GetAllSales();

MTRProject/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using MTRProject.Models

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager



<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="~/vendor.min.css" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MTR_Project</title>

    <environment include="Development">


    </environment>
    <environment exclude="Development">

        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <style>
        body > nav > button > span{
            color:white!important;
        }
        html, body {
            max-width: 100%;
            overflow-x: hidden;
        }
        .navactive {
            background-color: white;
            padding-bottom: 0px !important;
            margin-bottom: 0px !important;
        }

            .navactive a {
                color: black !important;
                background-color: white;
                border-radius: 15px !important;
            }
    </style>

    <div class="row">
        <div class="col-lg-12">
            <img src="~/images/mtrlogo.png" style="width: 250px; height:100px;" />
        </div>

    </div>


    <nav class="navbar navbar-expand-lg navbar-light  navbarStyles" style="background-color:#050505; padding-bottom:0px; width: 101% !important; ">
        <a class="navbar-brand" href="#">MedTech</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" style="color: white; background-color: white!important; margin-bottom: 5px;">
            <span class="navbar-toggler-icon" ></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item navactive">
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link" style="color:#FFFFFF; position: relative; ">Home</a>
                </li>

                @*<li class="nav-item ">
            <a asp-area="" asp-controller="SalesReps" asp-action="Index" class="nav-link" style="color:#FFFFFF;">Representatives</a>
        </li>*@
                <li class="nav-item ">
                    <a asp-area="" asp-controller="Sales" asp-action="Summary" class="nav-link" style="color:#FFFFFF;">Summary</a>
                </li>
                <li class="nav-item ">
                    <a asp-area="" asp-controller="Sales" asp-action="Index" class="nav-link" style="color:#FFFFFF;">Sales</a>
                </li>
                @*<li class="nav-item ">
            <a asp-area="" asp-controller="Account" asp-action="Index" class="nav-link" style="color:#FFFFFF;">Accounts</a>
        </li>*@
                <li class="nav-item ">
                    <a asp-area="" asp-controller="Customer" asp-action="Index" class="nav-link" style="color:#FFFFFF;">Customers</a>
                </li>
                <li class="nav-item ">
                    <a asp-area="" asp-controller="Vendor" asp-action="Index" class="nav-link" style="color:#FFFFFF;">Vendors</a>
                </li>
                <li class="nav-item ">
                    <a asp-area="" asp-controller="WeeklySaleItem" asp-action="Index" class="nav-link" style="color:#FFFFFF;">Weekly Sales</a>
                </li>
                <li class="nav-item ">
                    <a asp-area="" asp-controller="Admin" asp-action="Index" class="nav-link" style="color:#FFFFFF;">Admin</a>
                </li>
                <li class="nav-item ">
                    <a asp-area="" asp-controller="Manage" asp-action="Index" class="nav-link" style="color:#FFFFFF;">My Account</a>
                </li>

                @if (SignInManager.IsSignedIn(User))
    {
            <div>
                <form asp-area="" asp-controller="Account" asp-action="Logout" method="post" id="logoutForm" class="navbar-right">
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a asp-area="" asp-controller="Manage" asp-action="Index" title="Manage" class="nav-link" style="color:#FFFFFF; position:relative; left: 40%;">Hello @UserManager.GetUserName(User)!</a>
                        </li>
                        <li>
                            <button type="submit" class="btn btn-link navbar-btn navbar-link" class="nav-link" style="color:#FFFFFF;  position:relative; left: 90%">Log out</button>
                        </li>
                    </ul>
                </form>
            </div>
}
else
{
            <div style="position: relative; left: 60%;">
                <ul class="nav navbar-nav navbar-right">

                    <li class="nav-item "><a asp-area="" asp-controller="Account" asp-action="Register" style="color:#FFFFFF; position:relative; right: 75%" class="nav-link">Register</a></li>
                    <li class="nav-item "><a asp-area="" asp-controller="Account" asp-action="Login" style="color:#FFFFFF; position:relative; right: 75%" class="nav-link">Log in</a></li>


                </ul>
            </div>
}


                <!--<li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
        </div>
    </li>
    <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
    </li>-->
            </ul>

        </div>
    </nav>


    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - MTR_Project</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
    <script src="~/vendor.min.js"></script>

    <script>
        $('.nav').on('click', 'li', 'a', function () {
            $('.nav li').removeClass('active');
            $(this).addClass('active');
        });


    </script>
</body>
</html>