MTRProject/Models/Vendor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MTRProject.Models
{
    public class Vendor
    {
        public int VendorID { get; set; }
        [Required]
        public string Name { get; set; }

        [Required]
        public string Phone { get; set; }

        [Display(Name = "Login Name")]
        public string LoginName { get; set; }

        [Display(Name = "Login Password")]
        public string LoginPassword { get; set; }
        public string Comment { get; set; }
    }
}

MTRProject/Controllers/VendorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MTRProject.Data;
using MTRProject.Models;
using MTRProject.Repositories;

namespace MTRProject.Controllers
{
    public class VendorController : Controller
    {
        private IVendorRepository vendorRepo;

        public VendorController(IVendorRepository repo)
        {
            vendorRepo = repo;
        }

        // GET: Vendors


        public IActionResult Index()
        {
            return View(vendorRepo.GetAllVendors());
        }

        // GET: Sales/Details/5
        public IActionResult Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vendor = vendorRepo.GetVendorById(id);
            if (vendor == null)
            {
                return NotFound();
            }

            return View(vendor);
        }

        // GET: Vendor/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("VendorID,Name,Phone,LoginName,LoginPassword,Comment")] Vendor vendor)
        {
            if (ModelState.IsValid)
            {
                vendorRepo.AddVendor(vendor);
                return RedirectToAction(nameof(Index));
            }
            return View(vendor);
        }

        // GET: Vendor/Edit/5
        public IActionResult Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vendor = vendorRepo.GetVendorById(id);
            if (vendor == null)
            {
                return NotFound();
            }
            return View(vendor);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("VendorID,Name,Phone,LoginName,LoginPassword,Comment")] Vendor vendor)
        {
            if (id != vendor.VendorID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    vendorRepo.EditVendor(vendor);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VendorExists(vendor.VendorID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(vendor);
        }

        public IActionResult Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vendor = vendorRepo.GetVendorById(id);
            if (vendor == null)
            {
                return NotFound();
            }

            return View(vendor);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var vendor = vendorRepo.DeleteVendor(id);
            return RedirectToAction(nameof(Index));
        }

        private bool VendorExists(int id)
        {
            Vendor vendor = vendorRepo.GetVendorById(id);
            if (vendor != null)
                return true;
            else
                return false;
        }

    }
}

MTRProject/Views/Vendor/Create.cshtml
@model MTRProject.Models.Vendor


<body>


    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Phone" class="control-label"></label>
                    <input asp-for="Phone" class="form-control" />
                    <span asp-validation-for="Phone" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LoginName" class="control-label"></label>
                    <input asp-for="LoginName" class="form-control" />
                    <span asp-validation-for="LoginName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LoginPassword" class="control-label"></label>
                    <input asp-for="LoginPassword" class="form-control" />
                    <span asp-validation-for="LoginPassword" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Comment" class="control-label"></label>
                    <input asp-for="Comment" class="form-control" />
                    <span asp-validation-for="Comment" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }
</body>

MTRProject/Views/Vendor/Delete.cshtml
@model MTRProject.Models.Vendor


<body>
    <div style= "position:relative; left:30%;">
        <h3>Are you sure you want to delete this?</h3>
        <div>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Phone)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Phone)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.LoginName)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.LoginName)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.LoginPassword)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.LoginPassword)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Comment)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Comment)
                </dd>
            </dl>

            <form asp-action="Delete">
                <input type="hidden" asp-for="VendorID" />
                <input type="submit" value="Delete" class="btn btn-default" /> |
                <a asp-action="Index">Back to List</a>
            </form>
        </div>
        </div>
</body>

MTRProject/Views/Vendor/Details.cshtml
@model MTRProject.Models.Vendor

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>

    <div>
        <h4>Vendor</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Phone)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Phone)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.LoginName)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.LoginName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.LoginPassword)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.LoginPassword)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Comment)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Comment)
            </dd>
        </dl>
    </div>
    <div>
        <a asp-action="Edit" asp-route-id="@Model.VendorID">Edit</a> |
        <a asp-action="Index">Back to List</a>
    </div>
</body>
</html>

MTRProject/Views/Vendor/Edit.cshtml
@model MTRProject.Models.Vendor





<body>
    <div style="position:relative; left:25%;">
        <h4>Vendor</h4>
        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="VendorID" />
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Phone" class="control-label"></label>
                        <input asp-for="Phone" class="form-control" />
                        <span asp-validation-for="Phone" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="LoginName" class="control-label"></label>
                        <input asp-for="LoginName" class="form-control" />
                        <span asp-validation-for="LoginName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="LoginPassword" class="control-label"></label>
                        <input asp-for="LoginPassword" class="form-control" />
                        <span asp-validation-for="LoginPassword" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Comment" class="control-label"></label>
                        <input asp-for="Comment" class="form-control" />
                        <span asp-validation-for="Comment" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a asp-action="Index">Back to List</a>
        </div>

        @section Scripts {
            @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
        }
    </div>
</body>

MTRProject/Views/Vendor/Index.cshtml
@model IEnumerable<MTRProject.Models.Vendor>


<table class="table">
    <thead>
        <tr>
            
            <th>
                Name
            </th>
            <th>
                Phone
            </th>
            <th>
                Login Name
            </th>
            <th>
                Login Password
            </th>
            <th>
                Comment
            </th>
            <th>
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Phone)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LoginName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LoginPassword)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Comment)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.VendorID" class="btn btn-warning active">Edit</a>

                </td>
                <td>
                    <a asp-action="Delete" asp-route-id="@item.VendorID" class="btn btn-danger active">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<a asp-area="" asp-controller="Vendor" asp-action="Create" class="btn btn-primary">Add Vendor</a>